# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  port: 5433
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password: admin