# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  port: 5432
  adapter: postgresql
  encoding: unicode
  database: ghg
  pool: 5
  username: pbelouin
  password: s2lascap